@Server_HostAddress = http://localhost:5294

POST {{Server_HostAddress}}/users
Content-Type: application/json

{   
    "username": "Kaguyo",
    "email":"anything2@gmail.com",
    "password":"testAnything123"
}

###